apiVersion: v1
kind: ConfigMap
metadata:
  name: paysecure-config
  namespace: paysecure-prod
data:
  APP_ENV: "production"
  DB_HOST: "postgres-svc"
  DB_PORT: "5432"
  DB_NAME: "paysecure_db"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: paysecure-secret
  namespace: paysecure-prod
type: Opaque
data:
  # admin_user (base64)
  DB_USER: YWRtaW5fdXNlcg==
  # PaySecureProdPassword2026! (base64)
  DB_PASSWORD: UGF5U2VjdXJlUHJvZFBhc3N3b3JkMjAyNiE=