# ==============================================================================
# Microservice Module - Outputs
# Exposes provisioned resource identifiers, network DNS bindings, and endpoints.
# ==============================================================================

output "container_id" {
  description = "Unique 64-character identifier generated by Docker Engine."
  value       = docker_container.this.id
}

output "container_name" {
  description = "Assigned container name used for internal Docker DNS resolution."
  value       = docker_container.this.name
}

output "endpoint" {
  description = "Public HTTP endpoint reachable from the host (null if private)."
  value       = var.external_port > 0 ? "http://localhost:${var.external_port}" : null
}