name: "Terraform CI - Syntax & Plan"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  validate-and-plan:
    name: "Terraform CI & Plan"
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cloud-engineering-roadmap/Terraform/capstone-project

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Check Formatting
        run: terraform fmt -check -recursive

      #- name: Debug Exact OIDC Sub Claim
      #  run: |
      #    TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" -H "User-Agent: actions/runner" -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" | jq -r '.value')
      #    echo "=== KLAIM SUBJEK ASLI DARI RUNNER ==="
      #    echo "$TOKEN" | cut -d. -f2 | tr '_-' '/+' | base64 -d 2>/dev/null | jq -r '.sub'
      #    echo "====================================="

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubActionsSession
          aws-region: ap-southeast-1

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Syntax
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color